blank_issues_enabled: false
contact_links:
  - name: Janak Singh Dhami
    url: https://github.com/jsdhami
    about: Please ask and answer questions here.
  - name: JENUX SHOP
    url: https://dev.jsdhami.com.np
    about: Please report security vulnerabilities here.
