name: Auto Comment Merge Conflicts
on: push

permissions:
  pull-requests: write

jobs:
  auto-comment-merge-conflicts:
    runs-on: ubuntu-latest
    steps:
      - uses: codytseng/auto-comment-merge-conflicts@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          comment-body: 'Hey there, there is a merge conflict, can you take a look?'
          wait-ms: 3000
          max-retries: 5
          label-name: '🚨 merge conflict'
          ignore-authors: dependabot,otherAuthor
